### ISSUE TITLE
User warning in using babyai-text env

### ISSUE THREAD

**Issue by RZ-Q** [flowersteam/Grounding_LLMs_with_online_RL#12]
I have followed the README in babyai-text/ to install the env. But when i run the codes below:
'''
import gym
import babyai_text
env = gym.make("BabyAI_MixedTrainLocal")
'''
It turns out a lot of user warning:
<img width="1358" alt="image" src="https://github.com/flowersteam/Grounding_LLMs_with_online_RL/assets/62536298/22f04719-8c5a-4f9c-9333-bbbbeac7d755">

How to fix it?

**Comment by ClementRomac** [comment]
Hi,

I opened a [PR](https://github.com/flowersteam/Grounding_LLMs_with_online_RL/pull/13), could you please try it?

**Comment by RZ-Q** [comment]
OK，thank you，I will try it
