### ISSUE TITLE
BabyAI_MixedTrainLocal doesn't exist

### ISSUE THREAD

**Issue by Clayfigure** [flowersteam/Grounding_LLMs_with_online_RL#15]
I followed all the instructions but found the gym env doesn't exist.
![image](https://github.com/flowersteam/Grounding_LLMs_with_online_RL/assets/115345410/df6c7cc5-b358-4e49-9607-7ee439147b03)

**Comment by ClementRomac** [comment]
Hi,

I fixed the typos in BabyAI-Text's readme related to your first issue.
Concerning the second one, could you confirm [this PR](https://github.com/flowersteam/Grounding_LLMs_with_online_RL/pull/13) fixes it, please?

**Comment by Clayfigure** [comment]
OK, I have solved the problem. Thanks for your response.
