### ISSUE TITLE
Run without using slurm

### ISSUE THREAD

**Issue by Twilight92z** [flowersteam/Grounding_LLMs_with_online_RL#17]
I got 2 mistakes
The first is ModuleNotFoundError
`Traceback (most recent call last):
  File "/remote-home/btjiang/RL/Grounding_LLMs_with_online_RL/experiments/train_language_agent.py", line 27, in <module>
    from agents.drrn.drrn import DRRNAgent
  File "/remote-home/btjiang/RL/Grounding_LLMs_with_online_RL/experiments/agents/drrn/drrn.py", line 22, in <module>
    from experiments.agents.base_agent import BaseAgent
ModuleNotFoundError: No module named 'experiments'`
I have already pip installed everything as the readme file.

The second is something about accelerate
`Traceback (most recent call last):
  File "/remote-home/btjiang/RL/lamorel/lamorel/src/lamorel_launcher/launch.py", line 46, in main
    launch_command(accelerate_args)
  File "/remote-home/btjiang/anaconda3/envs/dlp/lib/python3.10/site-packages/accelerate/commands/launch.py", line 985, in launch_command
    multi_gpu_launcher(args)
  File "/remote-home/btjiang/anaconda3/envs/dlp/lib/python3.10/site-packages/accelerate/commands/launch.py", line 654, in multi_gpu_launcher
    distrib_run.run(args)
  File "/remote-home/btjiang/anaconda3/envs/dlp/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/remote-home/btjiang/anaconda3/envs/dlp/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/remote-home/btjiang/anaconda3/envs/dlp/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: `
It looks like it's caused by accelerate not being able to execute two processes correctly. How can I fix it?

**Comment by ClementRomac** [comment]
Hi,

How do you launch the project exactly?
As the module 'experiments' isn't found, it may be that the project is launched from inside this module, but I need to know the details on how you launch it to help you.

Concerning the second error, it seems you are using the lamorel_launcher which spawned (via accelerate and then torch distributed) processes. When one of these launched processes crashes (which is the case for you, this crash being caused by the first error you mention), torch distributed also crashes (which explains a second error in your stack trace). So this behavior is normal.

**Comment by Twilight92z** [comment]
I have solved the first problem.
As for the second issue, I'm not sure if I should add `lamorel_args.accelerate_args.machine_rank=1` to the launch command. I want to run it on a single machine with 4 GPUs. I see that you have mentioned the above parameter settings in the following places [lamorel issue 14](https://github.com/flowersteam/lamorel/issues/14)
If I launch two separate processes by hand like you mentioned in the issue(launch the example using a single GPU on a local machine). An error occurs because `main_process_port` in the default_config.yaml has already been called by a process and cannot be called repeatedly, it needs to be set to 0.
If i don't add the setting `lamorel_args.accelerate_args.machine_rank=1` after my launch command, I will get a `RuntimeError: Socket Timeout`

**Comment by Josh00-Lu** [comment]
> I have solved the first problem. As for the second issue, I'm not sure if I should add `lamorel_args.accelerate_args.machine_rank=1` to the launch command. I want to run it on a single machine with 4 GPUs. I see that you have mentioned the above parameter settings in the following places [lamorel issue 14](https://github.com/flowersteam/lamorel/issues/14) If I launch two separate processes by hand like you mentioned in the issue(launch the example using a single GPU on a local machine). An error occurs because `main_process_port` in the default_config.yaml has already been called by a process and cannot be called repeatedly, it needs to be set to 0. If i don't add the setting `lamorel_args.accelerate_args.machine_rank=1` after my launch command, I will get a `RuntimeError: Socket Timeout` My launch command is `python -m lamorel_launcher.launch --config-path /Grounding_LLMs_with_online_RL/experiments/configs/ --config-name local_gpu_config rl_script_args.path=/Grounding_LLMs_with_online_RL/experiments/train_language_agent.py lamorel_args.accelerate_args.machine_rank=1`

How do you solve the "ModuleNotFoundError: No module named 'experiments'" problem? Thanks very much!
