### ISSUE TITLE
Missing babyai.rl + string comparison syntax warning

### ISSUE THREAD

**Issue by vzhong** [flowersteam/Grounding_LLMs_with_online_RL#22]
Hi,

I've noticed the following problems in `babyai` repackaging:

1. In `setup.py`, `babyai.rl` is not included and therefore will not be installed (e.g. if installed from git)
2. there are many string comparisons in `babyai/levels/levelgen.py` and `babyai/levels/levelgen.py` using `is` and `is not`. These lead to `SyntaxWarning` such as `SyntaxWarning: "is not" with a literal` and should instead be `==` or `!=`.

**Comment by ClementRomac** [comment]
Hi,

Thanks for spotting this.
I am opening a PR, at least to fix the missing module.
