### ISSUE TITLE
How many actions are there in BabaAI-text environment? 

### ISSUE THREAD

**Issue by kiriwu** [flowersteam/Grounding_LLMs_with_online_RL#28]
For "BabyAI-MixedTrainLocal-v0", the action_space is Discrete(7),
while in experiments/configs/local_gpu_config.yaml,  the action_space is ["turn_left","turn_right","go_forward","pick_up","drop","toggle"], which is Discrete(6).

So how many actions are in "BabyAI-MixedTrainLocal-v0"? and what exact actions they are?
they are not  ["turn_left","turn_right","go_forward","pick_up","drop","toggle"]?

**Comment by ClementRomac** [comment]
Hi,

Our environment extends BabyAI, which has 7 actions: https://github.com/flowersteam/Grounding_LLMs_with_online_RL/blob/e2607ea8dd9d3d2b311285d28ee51d303d1e7f5e/babyai-text/gym-minigrid/gym_minigrid/minigrid.py#L651

The actions we specify in our config are the ones we authorize the LLM to score (we removed the "done" action from the list you show). Our code then parses this list and replaces underscores with spaces: https://github.com/flowersteam/Grounding_LLMs_with_online_RL/blob/e2607ea8dd9d3d2b311285d28ee51d303d1e7f5e/experiments/train_language_agent.py#L403
